In [1]:
import sys
sys.path.append('..')
import ast
import scipy.io
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
import statistics
import pandas as pd
import pickle
import os
from constant import path, parameter
from lib import evaluate

In [2]:
import warnings
warnings.filterwarnings('ignore')

# KNN,Naive Bayes,LogisticRegression algorithms

In [3]:
def training_models(models,features_train,targets_train,features_test):
    meta_proba = np.zeros((len(models) * 2, features_test.shape[0]))
    for i in range(len(models)):
        learner = models[i]
        learner.fit(features_train,targets_train)
        predictions_proba = learner.predict_proba(features_test)
        meta_proba[2*i][:] = predictions_proba.T[0]
        meta_proba[2*i + 1][:] = predictions_proba.T[1]
    meta_proba = meta_proba.transpose()
    return meta_proba

In [4]:
path.MODEL_PATH

'../model'

In [5]:
models = parameter.MODEL
models

[LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                    intercept_scaling=1, l1_ratio=None, max_iter=100,
                    multi_class='auto', n_jobs=None, penalty='l2',
                    random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                    warm_start=False),
 GaussianNB(priors=None, var_smoothing=1e-09),
 KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                      metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                      weights='uniform')]

In [6]:
models[0].fit([[1,2,3],[2,1,4],[1,1,0]],[1,2,3])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
from train import TrainMaster
train_master = TrainMaster()
for s in models:
    train_master.training_phase(model = s,features_train=[[1,2,3],[2,1,4],[1,1,0]],targets_train=[1,2,3])

----- Dump model LogisticRegression to success! -----
----- Dump model GaussianNB to success! -----
----- Dump model KNeighborsClassifier to success! -----


In [15]:
x = np.random.rand(10,6).reshape(10, 6)
# matrix = np.hsplit(x, 3)
# matrix
# combining = np.zeros((10,2))
# for i in range(3):
#     combining += matrix[i] 
# print(combining)
print(x)
rules = evaluate.Rules()
print(rules.combining_sum_rule(x, 2))
print(rules.combining_product_rule(x, 2))
print(rules.combining_max_min(x, 2, parameter ='max'))
print(rules.combining_max_min(x, 2, parameter ='min'))

[[0.05589496 0.94687181 0.97429958 0.1546169  0.44804312 0.38185898]
 [0.65349487 0.0036347  0.43536583 0.04519436 0.59036256 0.75410967]
 [0.49737587 0.11013221 0.20512766 0.45245352 0.70064576 0.9250191 ]
 [0.82842017 0.43282412 0.62725884 0.62791817 0.74141828 0.59476616]
 [0.27190686 0.98472502 0.7507166  0.16854511 0.19263967 0.22657017]
 [0.62679222 0.80958703 0.59846635 0.75059907 0.88880203 0.56482244]
 [0.50525847 0.24630014 0.32523531 0.81286499 0.80999612 0.34062907]
 [0.64707641 0.17472161 0.48449952 0.02925583 0.79259653 0.86747539]
 [0.83226892 0.81129977 0.50593926 0.01893632 0.19203148 0.97438745]
 [0.83174778 0.22463236 0.16322267 0.8335913  0.25145816 0.78400437]]
[[0.07017062 0.46497164 0.45205285]
 [0.23289641 0.19799909 0.39649183]
 [0.3166098  0.27025932 0.37671559]
 [0.48544612 0.39141413 0.40734167]
 [0.14681732 0.3924549  0.32576226]
 [0.45913043 0.56612969 0.38776293]
 [0.43937449 0.35209875 0.22195479]
 [0.22544408 0.32243938 0.4506583 ]
 [0.28373508 0.334443

# Caculate Mean and Variance

In [9]:
def combining_sum_product(matrix1, matrix2, matrix3):
    #Combining Algorithms use Sum Rules
    combining_sum_rule = matrix1 + matrix2 + matrix3
    combining_sum_rule = combining_sum_rule * 1/3   #Mean elements in matrix
    #Combining algorithms PRODUCT RULES
    combining_product_rule =  matrix1 * matrix2 * matrix3 * 1/3
    return combining_sum_rule,combining_product_rule

In [10]:
#Combining algorithms MIN RULES
#Function compare element row in matrix => Min value 
def min_element(value1, value2, value3):
    min_value = min([value1, value2, value3])
    return min_value 

def row_in_matrix(i,matrix_1, matrix_2, matrix_3):
    min_value_class1 = min_element(value1=matrix_1[i][0], value2=matrix_2[i][0], value3= matrix_3[i][0])
    min_value_class2 = min_element(value1=matrix_1[i][1], value2=matrix_2[i][1], value3= matrix_3[i][1])
    return min_value_class1, min_value_class2
    
def min_rule(matrix_1, matrix_2, matrix_3):
    combining_min_rule = np.zeros((matrix_1.shape))
    
    #Store variables to combining matrix
    for i in range(len(matrix_1)):
        combining_min_rule[i] = row_in_matrix(i, matrix_1=matrix_1,
                                         matrix_2=matrix_2,matrix_3=matrix_3)
    return combining_min_rule


In [11]:
#Combining algorithms MAX RULES
#Create variables to store combining matrix
def max_element(value1, value2, value3):
        max_value = max([value1, value2, value3])
        return max_value 
#Function compare element row in matrix => Max value 
def row_in_matrix(i,matrix_1, matrix_2, matrix_3):
        max_value_class1 = max_element(value1=matrix_1[i][0], value2=matrix_2[i][0], value3= matrix_3[i][0])
        max_value_class2 = max_element(value1=matrix_1[i][1], value2=matrix_2[i][1], value3= matrix_3[i][1])
        return max_value_class1, max_value_class2
    
def max_rule(matrix_1, matrix_2, matrix_3):
    combining_max_rule = np.zeros((matrix_1.shape))
    
    #Store variables to combining matrix
    for i in range(len(matrix_1)):
        combining_max_rule[i] = row_in_matrix(i, matrix_1=matrix_1,
                                             matrix_2=matrix_2,matrix_3=matrix_3)
    return combining_max_rule


In [12]:
def target(combining_matrix):
    targets_combining_algorithm = []
    for row in combining_matrix:
        result = 1 if row[0] > row[1] else 2
        targets_combining_algorithm.append(result)
    targets_combining_algorithm = np.asarray(targets_combining_algorithm)
    return targets_combining_algorithm
    
def error_combining_rule(target_combining_rule, target_test):
    boolen_result = []
    for i in range(len(target_test)):
        result = 1 if target_combining_rule[i] != target_test[i] else 0
        boolen_result.append(result)
    mean_combining_rule = statistics.mean(boolen_result)
#     variance_combining_rule = statistics.variance(boolen_result)
    return mean_combining_rule

In [13]:
def process_data_dat(filename_dat):
    samples = []
    data_set = [i.strip().split() for i in open("../data/" + filename_dat).readlines()] 
    for sample in data_set:
        res = ast.literal_eval(sample[0])
        sample = list(res)
        samples.append(sample)
    samples = np.asarray(samples)
    return samples

def process_cv_filename(cv_file):
    cv_mat = scipy.io.loadmat('../data/' + cv_file)
    return cv_mat['cv']

def split_train_test_by_id(data,cv_file, niters, nfolds):
    arrErrSum = []
    arrErrProd = []
    arrErrMax= []
    arrErrMin = []
    for i in range(niters):
        for j in range(nfolds):
            train_index = []
            cv_test = process_cv_filename(cv_file)
            test_index = cv_test[0][i*nfolds + j]
            test_index = np.concatenate(([i-1 for i in test_index]))
#             print("LOOP:",i*nfolds + j)
            train_index.append([i for i in range(len(data)) if i not in test_index]) 
            train_index = np.asarray(train_index[0])
#             print(data[train_index])
#             print(data[test_index])
            meta_proba = training_models(models,features_train=data[train_index][:,0:data.shape[1] - 1],
                               targets_train=data[train_index][:,-1], features_test=data[test_index][:,0:data.shape[1] - 1])
            predict_lr_proba = meta_proba[:,0:2]
            predict_gnb_proba = meta_proba[:,2:4]
            predict_knn_proba = meta_proba[:,4:6]
            #Caculate Mean and Variance by Sum Rules:
            combining_sum_rule,combining_product_rule = combining_sum_product(predict_lr_proba,predict_gnb_proba,
                                                                             predict_knn_proba)
            targets_combining_sum_rule = target(combining_sum_rule)
            mean_combining_sum_rule = error_combining_rule(targets_combining_sum_rule, data[test_index][:,-1] )
            arrErrSum.append(mean_combining_sum_rule)
            
            #Caculate Mean and Variance by Product Rules:
            targets_combining_product_rule = target(combining_product_rule)
            mean_combining_product_rule = error_combining_rule(targets_combining_product_rule, data[test_index][:,-1] )
            arrErrProd.append(mean_combining_product_rule)
            
            #Caculate Mean and Variance by Min Rules:
            combining_min_rule = min_rule(predict_lr_proba,predict_gnb_proba,predict_knn_proba)
            targets_combining_min_rule = target(combining_min_rule)
            mean_combining_min_rule = error_combining_rule(targets_combining_min_rule, data[test_index][:,-1] )
            arrErrMin.append(mean_combining_min_rule)
            
            #Caculate Mean and Variance by Max Rules:
            combining_max_rule = max_rule(predict_lr_proba,predict_gnb_proba,predict_knn_proba)
            targets_combining_max_rule = target(combining_max_rule)
            mean_combining_max_rule = error_combining_rule(targets_combining_max_rule, data[test_index][:,-1] )
            arrErrMax.append(mean_combining_max_rule)
#     #Caculate mean and variance Total Sum Rule
#     mean_sum = statistics.mean(arrErrSum)
#     variance_sum = statistics.variance(arrErrSum)
#     #Caculate mean and variance Total Product Rule
#     mean_product = statistics.mean(arrErrProd)
#     variance_product = statistics.variance(arrErrProd)
#     #Caculate mean and variance Total Min Rule
#     mean_min = statistics.mean(arrErrMin)
#     variance_min = statistics.variance(arrErrMin)
#     #Caculate mean and variance Total Max Rule
#     mean_max = statistics.mean(arrErrMax)
#     variance_max = statistics.variance(arrErrMax)
    
    pickle_file = {'Dataset':cv_file,'arrErrSum':arrErrSum,'arrErrProd':arrErrProd,
                   'arrErrMin':arrErrMin,'arrErrMax':arrErrMax}
#     pickle_file = {'Dataset':cv_file,'mean_sum':mean_sum,'variance_sum':variance_sum,
#                    'mean_product':mean_product,'variance_product':variance_product,
#                   'mean_min':mean_min,'variance_min':variance_min,
#                   'mean_max':mean_max,'variance_max':variance_max}
    print(pickle_file)
    pickle_out = open("dict_{}.pickle".format(cv_file),"wb")
    pickle.dump(pickle_file, pickle_out)
    pickle_out.close()
    
    

In [14]:
dataframe = []
for i in range(len(data_dat)):
    data = process_data_dat(data_dat[i])
    split_train_test_by_id(data,cv_filename[i],niters=3,nfolds=10)
    pickle_in = open("dict_{}.pickle".format(cv_filename[i]),"rb")
    example_dict = pickle.load(pickle_in)
    dataframe.append(example_dict)

NameError: name 'data_dat' is not defined

In [ ]:
import pandas as pd
data = pd.DataFrame.from_dict(dataframe)
data

In [ ]:
def mean_rules(cv_file,arrErrSum,arrErrProd,arrErrMin,arrErrMax):
    #Caculate mean and variance Total Sum Rule
    mean_sum = statistics.mean(arrErrSum)
    variance_sum = statistics.variance(arrErrSum)
    #Caculate mean and variance Total Product Rule
    mean_product = statistics.mean(arrErrProd)
    variance_product = statistics.variance(arrErrProd)
    #Caculate mean and variance Total Min Rule
    mean_min = statistics.mean(arrErrMin)
    variance_min = statistics.variance(arrErrMin)
    #Caculate mean and variance Total Max Rule
    mean_max = statistics.mean(arrErrMax)
    variance_max = statistics.variance(arrErrMax)
    dict_data = {'Dataset':cv_file,'mean_sum':mean_sum,'variance_sum':variance_sum,
                   'mean_product':mean_product,'variance_product':variance_product,
                  'mean_min':mean_min,'variance_min':variance_min,
                  'mean_max':mean_max,'variance_max':variance_max}
    return dict_data

In [ ]:
dict_data = []
for i in range(len(cv_filename)):
    dict_data.append(mean_rules(cv_filename[i],data['arrErrSum'][i],data['arrErrProd'][i],
                               data['arrErrMin'][i],data['arrErrMax'][i]))

In [ ]:
import pandas as pd
print('Bảng 1: Classification error của các fixed combining rule')
data_1 = pd.DataFrame.from_dict(dict_data)
data_1

In [ ]:
data['arrErrSum'][0]

# Caculate Win, Equal, Loss

In [ ]:
def win_compare_error(array1, array2):
#     win_result = []
    win_result = 0
    for i in range(len(array1)):
#         win_result.append(1 if array1[i] < array2[i] else 0)
        if (array1[i] < array2[i]):
            win_result += 1
    return win_result

def equal_compare_error(array1, array2):
    equal_result = 0
    for i in range(len(array1)):
        if (array1[i] == array2[i]):
            equal_result += 1
    return equal_result

def loss_compare_error(array1, array2):
    loss_result = 0
    for i in range(len(array1)):
        if (array1[i] > array2[i]):
            loss_result += 1
    return loss_result

In [ ]:
len(data['arrErrSum'][2])

In [ ]:
final_results = []
for i in range(len(cv_filename)):
    # Sum vs Product
    win_compare_sum_prod = win_compare_error(data['arrErrSum'][i],data['arrErrProd'][i])
    print(win_compare_sum_prod)
    equal_compare_sum_prod = equal_compare_error(data['arrErrSum'][i],data['arrErrProd'][i])
    loss_compare_sum_prod = loss_compare_error(data['arrErrSum'][i],data['arrErrProd'][i])
    # Sum vs Min
    win_compare_sum_min = win_compare_error(data['arrErrSum'][i],data['arrErrMin'][i])
    print(win_compare_sum_min)
    equal_compare_sum_min = equal_compare_error(data['arrErrSum'][i],data['arrErrMin'][i])
    loss_compare_sum_min = loss_compare_error(data['arrErrSum'][i],data['arrErrMin'][i])
    # Sum vs Max
    win_compare_sum_max = win_compare_error(data['arrErrSum'][i],data['arrErrMax'][i])
    equal_compare_sum_max = equal_compare_error(data['arrErrSum'][i],data['arrErrMax'][i])
    loss_compare_sum_max = loss_compare_error(data['arrErrSum'][i],data['arrErrMax'][i])
    dict_result = {'Dataset':cv_filename[i],'win_sum_prod':win_compare_sum_prod,'equal_sum_prod':equal_compare_sum_prod,
                  'loss_sum_prod':loss_compare_sum_prod,'win_sum_min':win_compare_sum_min,'equal_sum_min':equal_compare_sum_min,
                  'loss_sum_min':loss_compare_sum_min,'win_sum_max':win_compare_sum_max,'equal_sum_max':equal_compare_sum_max,
                  'loss_sum_max':loss_compare_sum_max}
    print(dict_result)
    final_results.append(dict_result)

In [ ]:
import scipy
#Wilcoxon Sum vs Other Rules
print("DATA: cv_australian.mat")
print("Wilcoxon Sum vs Product Rules:",scipy.stats.wilcoxon(data['arrErrSum'][0],data['arrErrProd'][0],zero_method='wilcox'))
print("Wilcoxon Sum vs Min Rules:",scipy.stats.wilcoxon(data['arrErrSum'][0],data['arrErrMin'][0],zero_method='wilcox'))
print("Wilcoxon Sum vs Max Rules:",scipy.stats.wilcoxon(data['arrErrSum'][0],data['arrErrMax'][0],zero_method='wilcox'))

In [ ]:
print("DATA: cv_bupa.mat")
print("Wilcoxon Sum vs Product Rules:",scipy.stats.wilcoxon(data['arrErrSum'][1],data['arrErrProd'][1],zero_method='wilcox'))
print("Wilcoxon Sum vs Min Rules:",scipy.stats.wilcoxon(data['arrErrSum'][1],data['arrErrMin'][1],zero_method='wilcox'))
print("Wilcoxon Sum vs Max Rules:",scipy.stats.wilcoxon(data['arrErrSum'][1],data['arrErrMax'][1],zero_method='wilcox'))

In [ ]:
print("DATA: cv_glass.mat")
print("Wilcoxon Sum vs Product Rules:",scipy.stats.wilcoxon(data['arrErrSum'][2],data['arrErrProd'][2],zero_method='wilcox'))
print("Wilcoxon Sum vs Min Rules:",scipy.stats.wilcoxon(data['arrErrSum'][2],data['arrErrMin'][2],zero_method='wilcox'))
print("Wilcoxon Sum vs Max Rules:",scipy.stats.wilcoxon(data['arrErrSum'][2],data['arrErrMax'][2],zero_method='wilcox'))

In [ ]:
import pandas as pd
print('Bảng 2: Kết quả kiểm định')
data_2 = pd.DataFrame.from_dict(final_results)
data_2