In [1]:
import csv
import numpy as np
import ast
import json
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [2]:
import warnings
warnings.filterwarnings('ignore')

# Preapre Data

In [3]:
data_train_austradian = [i.strip().split() for i in open("australian_train1.dat").readlines()] 
data_test_austradian = [i.strip().split() for i in open("australian_test.dat").readlines()]

In [4]:
def process_feature(observe):
    res = ast.literal_eval(observe[0])
    feature_observe = list(res)[:len(observe) - 2]
    label_observe = list(res)[-1]
    return feature_observe,label_observe

In [5]:
labels_train = []
features_train = []
for i, sample in enumerate(data_train_austradian):
    feature_train_sample, label_train_sample = process_feature(sample)
    features_train.append(feature_train_sample)
    labels_train.append(label_train_sample)
# Covert to array
features_train = np.asarray(features_train)    #Shape matrix 386 * 14
labels_train = np.asarray(labels_train)        #Shape matrix 386 * 1

# Process Test Data
features_test = []
labels_test = []
for i, sample in enumerate(data_test_austradian):
    feature_test_sample, label_test_data = process_feature(sample)
    features_test.append(feature_test_sample)
    labels_test.append(label_test_data)
#Covert to array
features_test = np.asarray(features_test)      #Shape matrix 207 * 14
labels_test = np.asarray(labels_test)          #Shape matrix 207 * 1
print(features_test.shape)
print(labels_test.shape)

(207, 14)
(207,)


# KNN,Naive Bayes,LogisticRegression algorithms

In [6]:
# KNN algorithms
clf = neighbors.KNeighborsClassifier(n_neighbors=10,p = 2)
clf.fit(features_train,labels_train)
label_predict_knn_prob = clf.predict_proba(features_test)# probability in class
label_predict_knn = clf.predict(features_test) 

In [7]:
print('Accuracy Score for KNN Algorithm: {}'.format(100*accuracy_score(label_predict_knn, labels_test)))

Accuracy Score for KNN Algorithm: 68.59903381642512


In [8]:
label_predict_knn_prob

array([[0.6, 0.4],
       [0.5, 0.5],
       [0.2, 0.8],
       [0.6, 0.4],
       [0.5, 0.5],
       [0.3, 0.7],
       [0.1, 0.9],
       [0.4, 0.6],
       [0.3, 0.7],
       [0.4, 0.6],
       [0.7, 0.3],
       [0.3, 0.7],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.1, 0.9],
       [1. , 0. ],
       [0.2, 0.8],
       [0.7, 0.3],
       [0. , 1. ],
       [0.6, 0.4],
       [0.3, 0.7],
       [0.5, 0.5],
       [0.4, 0.6],
       [0.3, 0.7],
       [0.4, 0.6],
       [1. , 0. ],
       [0.5, 0.5],
       [0.1, 0.9],
       [0.3, 0.7],
       [1. , 0. ],
       [0.3, 0.7],
       [0.2, 0.8],
       [0.7, 0.3],
       [0.5, 0.5],
       [0.4, 0.6],
       [0.7, 0.3],
       [0.2, 0.8],
       [0.3, 0.7],
       [0.3, 0.7],
       [0.2, 0.8],
       [0.1, 0.9],
       [0.4, 0.6],
       [0.3, 0.7],
       [0. , 1. ],
       [0.4, 0.6],
       [0.2, 0.8],
       [0.2, 0.8],
       [1. , 0. ],
       [0.4, 0.6],
       [0. , 1. ],
       [0.3,

In [9]:
label_predict_knn_prob[:,0]

array([0.6, 0.5, 0.2, 0.6, 0.5, 0.3, 0.1, 0.4, 0.3, 0.4, 0.7, 0.3, 0.5,
       0.5, 0.6, 0.6, 0.1, 1. , 0.2, 0.7, 0. , 0.6, 0.3, 0.5, 0.4, 0.3,
       0.4, 1. , 0.5, 0.1, 0.3, 1. , 0.3, 0.2, 0.7, 0.5, 0.4, 0.7, 0.2,
       0.3, 0.3, 0.2, 0.1, 0.4, 0.3, 0. , 0.4, 0.2, 0.2, 1. , 0.4, 0. ,
       0.3, 0.7, 0.3, 0.2, 0.1, 0.4, 0.7, 0.3, 0.6, 0.8, 0.7, 0.2, 0.4,
       0.1, 0.3, 0.3, 0.4, 0.7, 0.3, 0.2, 0.6, 0.3, 0.1, 0.2, 0.5, 0.5,
       0.9, 0.7, 0.7, 0.2, 0.3, 0.6, 0.4, 0.6, 0.6, 0.1, 0.3, 0.5, 0.4,
       0.2, 0. , 0.7, 0.6, 0.1, 0.6, 0.5, 0.7, 0.4, 0.5, 0.3, 0.8, 0. ,
       0.4, 0.3, 0.9, 0.6, 0.3, 1. , 0.2, 0. , 0.2, 0.3, 0.2, 0.1, 0.1,
       0.3, 0.2, 0.8, 0.5, 0.7, 0.4, 0.3, 0.4, 0.6, 0.2, 0.6, 0.4, 0.5,
       0.5, 0.4, 0.6, 0.3, 0.2, 0.7, 0.7, 0.2, 0.8, 0.7, 0.2, 0.3, 0.3,
       0.5, 0.9, 0.4, 0.2, 0.2, 0.4, 0.2, 0.9, 0.4, 0. , 0.3, 0.3, 0.5,
       0.7, 0. , 0.3, 0.2, 0.3, 0.2, 0.6, 0.3, 0.3, 0.6, 0.2, 0.5, 0.4,
       0.5, 0.4, 0.6, 0.2, 0.6, 0.3, 0.8, 0.7, 0.7, 0.2, 0.3, 0.

In [10]:
#Naive Bayes algorithm
gnb = GaussianNB()
gnb.fit(features_train,labels_train)
label_predict_gnb = gnb.predict(features_test)
label_predict_gnb_prob = gnb.predict_proba(features_test)

In [11]:
print('Accuracy Score for Naive Bayes Algorithm: {}'.format(100*accuracy_score(label_predict_gnb, labels_test)))

Accuracy Score for Naive Bayes Algorithm: 80.67632850241546


In [12]:
#LogisticRegression algorithms
clf = LogisticRegression(random_state=0)
clf.fit(features_train,labels_train)
label_predict_lr = clf.predict(features_test)
label_predict_lr_prob = clf.predict_proba(features_test)

In [13]:
print('Accuracy Score for LogisticRegression algorithms: {}'.format(100*accuracy_score(label_predict_lr, labels_test)))

Accuracy Score for LogisticRegression algorithms: 78.74396135265701


# Combining Algorithms

Combining Algorithms use Sum Rules

In [14]:
combining_sum_rule = label_predict_knn_prob + label_predict_gnb_prob + label_predict_lr_prob

In [15]:
combining_sum_rule = combining_sum_rule * 1/3   #Mean elements in matrix

In [16]:
labels_combining_algorithm = []
for row in combining_sum_rule:
    result = 1 if row[0] > row [1] else 2
    labels_combining_algorithm.append(result)
labels_combining_algorithm = np.asarray(labels_combining_algorithm)

In [17]:
labels_combining_algorithm

array([1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2,
       2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1,
       1, 1, 2, 2, 2, 2, 1, 2, 1])

# Evaluatation

In [18]:
print('Accuracy Score for Combining Algorithm: {}'.format(100*accuracy_score(labels_combining_algorithm, labels_test)))

Accuracy Score for Combining Algorithm: 81.15942028985508


In [19]:
target_names = ['class 1','class 2']
print(classification_report(labels_test, labels_combining_algorithm, target_names=target_names))

              precision    recall  f1-score   support

     class 1       0.85      0.63      0.72        81
     class 2       0.80      0.93      0.86       126

    accuracy                           0.81       207
   macro avg       0.82      0.78      0.79       207
weighted avg       0.82      0.81      0.80       207



# Statistical Inference: Kiểm định giả thuyết thống kê (Hypothesis Testing)

Combining algorithms SUM RULES

In [20]:
combining_sum_rule.shape

(207, 2)

Combining algorithms PRODUCT RULES

In [21]:
combining_product_rule = label_predict_knn_prob * label_predict_gnb_prob * label_predict_lr_prob

Combining algorithms MAX RULES 

In [22]:
#Create variables to store combining matrix
combining_max_rule = np.zeros((combining_sum_rule.shape))

#Function compare element row in matrix => Max value 
def max_element(value1, value2, value3):
    max_value = max([value1, value2, value3])
    return max_value 
def row_in_matrix(i,matrix_1, matrix_2, matrix_3):
    max_value_class1 = max_element(value1=matrix_1[i][0], value2=matrix_2[i][0], value3= matrix_3[i][0])
    max_value_class2 = max_element(value1=matrix_1[i][1], value2=matrix_2[i][1], value3= matrix_3[i][1])
    return max_value_class1, max_value_class2
#Store variables to combining matrix
for i in range(len(label_predict_knn_prob)):
    combining_max_rule[i] = row_in_matrix(i, matrix_1=label_predict_knn_prob,
                                         matrix_2=label_predict_gnb_prob,matrix_3=label_predict_lr_prob)

In [23]:
combining_max_rule.shape

(207, 2)

Combining algorithms MIN RULES

In [24]:
#Create variables to store combining matrix
combining_min_rule = np.zeros((combining_sum_rule.shape))

#Function compare element row in matrix => Min value 
def min_element(value1, value2, value3):
    min_value = min([value1, value2, value3])
    return min_value 
def row_in_matrix(i,matrix_1, matrix_2, matrix_3):
    min_value_class1 = min_element(value1=matrix_1[i][0], value2=matrix_2[i][0], value3= matrix_3[i][0])
    min_value_class2 = min_element(value1=matrix_1[i][1], value2=matrix_2[i][1], value3= matrix_3[i][1])
    return min_value_class1, min_value_class2
#Store variables to combining matrix
for i in range(len(label_predict_knn_prob)):
    combining_min_rule[i] = row_in_matrix(i, matrix_1=label_predict_knn_prob,
                                         matrix_2=label_predict_gnb_prob,matrix_3=label_predict_lr_prob)

In [25]:
combining_min_rule.shape

(207, 2)

def majority_vote(votes):
    majority = None
    majority_count = 0
    for vote in votes:
        if majority_count == 0:
            majority = vote
        if vote == majority:
            majority_count += 1
        else:
            majority_count -= 1
    return majority

# votes = list of integer votes
def majority1_vote(votes):
    majority = None
    majority_count = 0
    for vote in votes:
        vote_count = 0
        for other_vote in votes:
            if vote == other_vote:
                vote_count += 1
        if vote_count > majority_count:
            majority = vote
            majority_count = vote_count
    return majority

votes = [1,2,3,4,4,3]
print(majority_vote(votes))

majority1_vote(votes)


In [46]:
combining_sum_rule.shape

(207, 2)

## Caculate Mean and Variance 

In [99]:
import statistics

def target(combining_rule):
    targets_combining_algorithm = []
    for row in combining_rule:
        result = 1 if row[0] > row[1] else 2
        targets_combining_algorithm.append(result)
    targets_combining_algorithm = np.asarray(targets_combining_algorithm)
    return targets_combining_algorithm
    
def error_combining_rule(target_combining_rule, target_test):
    boolen_result = []
    for i in range(len(target_test)):
        result = 1 if target_combining_rule[i] != target_test[i] else 0
        boolen_result.append(result)
    mean_combining_rule = statistics.mean(boolen_result)
    variance_combining_rule = statistics.variance(boolen_result)
    return mean_combining_rule, variance_combining_rule

## Error SUM

In [100]:
targets_combining_sum_rule = target(combining_sum_rule)
mean_combining_sum_rule, variance_combining_sum_rule = error_combining_rule(targets_combining_sum_rule,labels_test )

## Error PRODUCT

In [ ]:
targets_combining_product_rule = target(combining_product_rule)
mean_combining_product_rule, variance_combining_sum_rule = error_combining_rule(targets_combining_sum_rule,labels_test )