In [1]:
import csv
import numpy as np
import ast
import json
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [2]:
import warnings
warnings.filterwarnings('ignore')

# Preapre Data

In [3]:
data_train_austradian = [i.strip().split() for i in open("australian_train1.dat").readlines()] 
data_test_austradian = [i.strip().split() for i in open("australian_test.dat").readlines()]

In [4]:
def process_feature(observe):
    res = ast.literal_eval(observe[0])
    feature_observe = list(res)[:len(observe) - 2]
    label_observe = list(res)[-1]
    return feature_observe,label_observe

In [5]:
labels_train = []
features_train = []
for i, sample in enumerate(data_train_austradian):
    feature_train_sample, label_train_sample = process_feature(sample)
    features_train.append(feature_train_sample)
    labels_train.append(label_train_sample)
# Covert to array
features_train = np.asarray(features_train)    #Shape matrix 386 * 14
labels_train = np.asarray(labels_train)        #Shape matrix 386 * 1

# Process Test Data
features_test = []
labels_test = []
for i, sample in enumerate(data_test_austradian):
    feature_test_sample, label_test_data = process_feature(sample)
    features_test.append(feature_test_sample)
    labels_test.append(label_test_data)
#Covert to array
features_test = np.asarray(features_test)      #Shape matrix 207 * 14
labels_test = np.asarray(labels_test)          #Shape matrix 207 * 1
print(features_test.shape)
print(labels_test.shape)

(207, 14)
(207,)


# KNN,Naive Bayes,LogisticRegression algorithms

In [6]:
# KNN algorithms
clf = neighbors.KNeighborsClassifier(n_neighbors=10,p = 2)
clf.fit(features_train,labels_train)
label_predict_knn_prob = clf.predict_proba(features_test)# probability in class
label_predict_knn = clf.predict(features_test) 

In [7]:
print('Accuracy Score for KNN Algorithm: {}'.format(100*accuracy_score(label_predict_knn, labels_test)))

Accuracy Score for KNN Algorithm: 68.59903381642512


In [26]:
label_predict_knn_prob

array([[0.6, 0.4],
       [0.5, 0.5],
       [0.2, 0.8],
       [0.6, 0.4],
       [0.5, 0.5],
       [0.3, 0.7],
       [0.1, 0.9],
       [0.4, 0.6],
       [0.3, 0.7],
       [0.4, 0.6],
       [0.7, 0.3],
       [0.3, 0.7],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.1, 0.9],
       [1. , 0. ],
       [0.2, 0.8],
       [0.7, 0.3],
       [0. , 1. ],
       [0.6, 0.4],
       [0.3, 0.7],
       [0.5, 0.5],
       [0.4, 0.6],
       [0.3, 0.7],
       [0.4, 0.6],
       [1. , 0. ],
       [0.5, 0.5],
       [0.1, 0.9],
       [0.3, 0.7],
       [1. , 0. ],
       [0.3, 0.7],
       [0.2, 0.8],
       [0.7, 0.3],
       [0.5, 0.5],
       [0.4, 0.6],
       [0.7, 0.3],
       [0.2, 0.8],
       [0.3, 0.7],
       [0.3, 0.7],
       [0.2, 0.8],
       [0.1, 0.9],
       [0.4, 0.6],
       [0.3, 0.7],
       [0. , 1. ],
       [0.4, 0.6],
       [0.2, 0.8],
       [0.2, 0.8],
       [1. , 0. ],
       [0.4, 0.6],
       [0. , 1. ],
       [0.3,

In [27]:
label_predict_knn_prob[:,0]

array([0.6, 0.5, 0.2, 0.6, 0.5, 0.3, 0.1, 0.4, 0.3, 0.4, 0.7, 0.3, 0.5,
       0.5, 0.6, 0.6, 0.1, 1. , 0.2, 0.7, 0. , 0.6, 0.3, 0.5, 0.4, 0.3,
       0.4, 1. , 0.5, 0.1, 0.3, 1. , 0.3, 0.2, 0.7, 0.5, 0.4, 0.7, 0.2,
       0.3, 0.3, 0.2, 0.1, 0.4, 0.3, 0. , 0.4, 0.2, 0.2, 1. , 0.4, 0. ,
       0.3, 0.7, 0.3, 0.2, 0.1, 0.4, 0.7, 0.3, 0.6, 0.8, 0.7, 0.2, 0.4,
       0.1, 0.3, 0.3, 0.4, 0.7, 0.3, 0.2, 0.6, 0.3, 0.1, 0.2, 0.5, 0.5,
       0.9, 0.7, 0.7, 0.2, 0.3, 0.6, 0.4, 0.6, 0.6, 0.1, 0.3, 0.5, 0.4,
       0.2, 0. , 0.7, 0.6, 0.1, 0.6, 0.5, 0.7, 0.4, 0.5, 0.3, 0.8, 0. ,
       0.4, 0.3, 0.9, 0.6, 0.3, 1. , 0.2, 0. , 0.2, 0.3, 0.2, 0.1, 0.1,
       0.3, 0.2, 0.8, 0.5, 0.7, 0.4, 0.3, 0.4, 0.6, 0.2, 0.6, 0.4, 0.5,
       0.5, 0.4, 0.6, 0.3, 0.2, 0.7, 0.7, 0.2, 0.8, 0.7, 0.2, 0.3, 0.3,
       0.5, 0.9, 0.4, 0.2, 0.2, 0.4, 0.2, 0.9, 0.4, 0. , 0.3, 0.3, 0.5,
       0.7, 0. , 0.3, 0.2, 0.3, 0.2, 0.6, 0.3, 0.3, 0.6, 0.2, 0.5, 0.4,
       0.5, 0.4, 0.6, 0.2, 0.6, 0.3, 0.8, 0.7, 0.7, 0.2, 0.3, 0.

In [8]:
#Naive Bayes algorithm
gnb = GaussianNB()
gnb.fit(features_train,labels_train)
label_predict_gnb = gnb.predict(features_test)
label_predict_gnb_prob = gnb.predict_proba(features_test)

In [9]:
print('Accuracy Score for Naive Bayes Algorithm: {}'.format(100*accuracy_score(label_predict_gnb, labels_test)))

Accuracy Score for Naive Bayes Algorithm: 80.67632850241546


In [10]:
#LogisticRegression algorithms
clf = LogisticRegression(random_state=0)
clf.fit(features_train,labels_train)
label_predict_lr = clf.predict(features_test)
label_predict_lr_prob = clf.predict_proba(features_test)

In [11]:
print('Accuracy Score for LogisticRegression algorithms: {}'.format(100*accuracy_score(label_predict_lr, labels_test)))

Accuracy Score for LogisticRegression algorithms: 78.74396135265701


# Combining Algorithms

In [12]:
combining_algorithms = np.concatenate((label_predict_knn_prob,label_predict_gnb_prob,label_predict_lr_prob),axis = 1)

In [13]:
combining_algorithms

array([[6.00000000e-001, 4.00000000e-001, 9.99179948e-001,
        8.20052462e-004, 6.14262837e-001, 3.85737163e-001],
       [5.00000000e-001, 5.00000000e-001, 1.62585667e-004,
        9.99837414e-001, 9.79595798e-002, 9.02040420e-001],
       [2.00000000e-001, 8.00000000e-001, 3.17650342e-002,
        9.68234966e-001, 3.04463902e-001, 6.95536098e-001],
       ...,
       [3.00000000e-001, 7.00000000e-001, 9.94705280e-001,
        5.29471965e-003, 5.39375247e-001, 4.60624753e-001],
       [6.00000000e-001, 4.00000000e-001, 2.91175400e-001,
        7.08824600e-001, 1.26278190e-001, 8.73721810e-001],
       [1.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        1.09586607e-111, 9.99982859e-001, 1.71406573e-005]])

In [14]:
sum_prob_sample = []
for i,row in enumerate(combining_algorithms):
    sum_prob_sample.append([np.mean((row[0], row [2], row[4])),
                           np.mean((row[1], row[3], row[5]))])
sum_prob_sample = np.asarray(sum_prob_sample)  

In [15]:
def compare_prob(a,b):
    result = 1 if (a>b) else 2
    return result

In [16]:
labels_combining_algorithm = []
for row in sum_prob_sample:
    result = compare_prob(row[0], row[1])
    labels_combining_algorithm.append(result)
labels_combining_algorithm = np.asarray(labels_combining_algorithm)

# Evaluate

In [17]:
print('Accuracy Score for Combining Algorithm: {}'.format(100*accuracy_score(labels_combining_algorithm, labels_test)))

Accuracy Score for Combining Algorithm: 81.15942028985508


In [18]:
target_names = ['class 1','class 2']
print(classification_report(labels_test, labels_combining_algorithm, target_names=target_names))

              precision    recall  f1-score   support

     class 1       0.85      0.63      0.72        81
     class 2       0.80      0.93      0.86       126

    accuracy                           0.81       207
   macro avg       0.82      0.78      0.79       207
weighted avg       0.82      0.81      0.80       207

